# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/first_attempt.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(851, 934)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_dilate = QtWidgets.QLabel(self.tab)
        self.label_dilate.setObjectName("label_dilate")
        self.horizontalLayout.addWidget(self.label_dilate)
        self.hslider_dilate = QtWidgets.QSlider(self.tab)
        self.hslider_dilate.setMinimum(-10)
        self.hslider_dilate.setMaximum(10)
        self.hslider_dilate.setPageStep(1)
        self.hslider_dilate.setTracking(False)
        self.hslider_dilate.setOrientation(QtCore.Qt.Horizontal)
        self.hslider_dilate.setInvertedAppearance(False)
        self.hslider_dilate.setInvertedControls(False)
        self.hslider_dilate.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.hslider_dilate.setObjectName("hslider_dilate")
        self.horizontalLayout.addWidget(self.hslider_dilate)
        self.checkBox_livePreview = QtWidgets.QCheckBox(self.tab)
        self.checkBox_livePreview.setChecked(True)
        self.checkBox_livePreview.setObjectName("checkBox_livePreview")
        self.horizontalLayout.addWidget(self.checkBox_livePreview)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_col_cutoff = QtWidgets.QLabel(self.tab)
        self.label_col_cutoff.setObjectName("label_col_cutoff")
        self.horizontalLayout_2.addWidget(self.label_col_cutoff)
        self.doubleSpinBox_col_cutoff = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_col_cutoff.setMinimum(0.01)
        self.doubleSpinBox_col_cutoff.setMaximum(0.2)
        self.doubleSpinBox_col_cutoff.setSingleStep(0.01)
        self.doubleSpinBox_col_cutoff.setProperty("value", 0.1)
        self.doubleSpinBox_col_cutoff.setObjectName("doubleSpinBox_col_cutoff")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_col_cutoff)
        self.label_col_plateau = QtWidgets.QLabel(self.tab)
        self.label_col_plateau.setObjectName("label_col_plateau")
        self.horizontalLayout_2.addWidget(self.label_col_plateau)
        self.spinBox_col_plateau = QtWidgets.QSpinBox(self.tab)
        self.spinBox_col_plateau.setMinimum(1)
        self.spinBox_col_plateau.setMaximum(25)
        self.spinBox_col_plateau.setProperty("value", 10)
        self.spinBox_col_plateau.setObjectName("spinBox_col_plateau")
        self.horizontalLayout_2.addWidget(self.spinBox_col_plateau)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_row_cutoff = QtWidgets.QLabel(self.tab)
        self.label_row_cutoff.setObjectName("label_row_cutoff")
        self.horizontalLayout_3.addWidget(self.label_row_cutoff)
        self.doubleSpinBox_row_cutoff = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_row_cutoff.setMinimum(0.01)
        self.doubleSpinBox_row_cutoff.setMaximum(0.2)
        self.doubleSpinBox_row_cutoff.setSingleStep(0.01)
        self.doubleSpinBox_row_cutoff.setProperty("value", 0.1)
        self.doubleSpinBox_row_cutoff.setObjectName("doubleSpinBox_row_cutoff")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_row_cutoff)
        self.label_row_plateau = QtWidgets.QLabel(self.tab)
        self.label_row_plateau.setObjectName("label_row_plateau")
        self.horizontalLayout_3.addWidget(self.label_row_plateau)
        self.spinBox_row_plateau = QtWidgets.QSpinBox(self.tab)
        self.spinBox_row_plateau.setMinimum(1)
        self.spinBox_row_plateau.setProperty("value", 5)
        self.spinBox_row_plateau.setObjectName("spinBox_row_plateau")
        self.horizontalLayout_3.addWidget(self.spinBox_row_plateau)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.button_drawTable = QtWidgets.QPushButton(self.tab)
        self.button_drawTable.setObjectName("button_drawTable")
        self.verticalLayout_4.addWidget(self.button_drawTable)
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 809, 697))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_preprocess = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_preprocess.setText("")
        self.label_preprocess.setObjectName("label_preprocess")
        self.verticalLayout_2.addWidget(self.label_preprocess)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_dilate_2 = QtWidgets.QLabel(self.tab_2)
        self.label_dilate_2.setObjectName("label_dilate_2")
        self.horizontalLayout_4.addWidget(self.label_dilate_2)
        self.hslider_dilate_2 = QtWidgets.QSlider(self.tab_2)
        self.hslider_dilate_2.setMinimum(-10)
        self.hslider_dilate_2.setMaximum(10)
        self.hslider_dilate_2.setPageStep(1)
        self.hslider_dilate_2.setTracking(False)
        self.hslider_dilate_2.setOrientation(QtCore.Qt.Horizontal)
        self.hslider_dilate_2.setInvertedAppearance(False)
        self.hslider_dilate_2.setInvertedControls(False)
        self.hslider_dilate_2.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.hslider_dilate_2.setObjectName("hslider_dilate_2")
        self.horizontalLayout_4.addWidget(self.hslider_dilate_2)
        self.checkBox_livePreview_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_livePreview_2.setChecked(True)
        self.checkBox_livePreview_2.setObjectName("checkBox_livePreview_2")
        self.horizontalLayout_4.addWidget(self.checkBox_livePreview_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.button_detect_chars = QtWidgets.QPushButton(self.tab_2)
        self.button_detect_chars.setObjectName("button_detect_chars")
        self.verticalLayout_6.addWidget(self.button_detect_chars)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 809, 763))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_preprocess_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_preprocess_2.setText("")
        self.label_preprocess_2.setObjectName("label_preprocess_2")
        self.verticalLayout_5.addWidget(self.label_preprocess_2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_dilate.setText(_translate("MainWindow", "Dilate Image"))
        self.checkBox_livePreview.setText(_translate("MainWindow", "Live Preview"))
        self.label_col_cutoff.setText(_translate("MainWindow", "Column Cutoff"))
        self.label_col_plateau.setText(_translate("MainWindow", "Column Plateau"))
        self.label_row_cutoff.setText(_translate("MainWindow", "Row Cutoff"))
        self.label_row_plateau.setText(_translate("MainWindow", "Row Plateau"))
        self.button_drawTable.setText(_translate("MainWindow", "Draw Table"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Configure Table"))
        self.label_dilate_2.setText(_translate("MainWindow", "Dilate Image"))
        self.checkBox_livePreview_2.setText(_translate("MainWindow", "Live Preview"))
        self.button_detect_chars.setText(_translate("MainWindow", "Detect Characters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Data Extraction"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

